// Generated by CoffeeScript 1.4.0
(function() {
  var blog, helper;

  require('should');

  helper = (require('../modules/helper'))();

  blog = require(__dirname + '/init');

  describe('Blog', function() {
    return describe('findPost', function() {
      var expected, _id;
      expected = 'test post';
      _id = '';
      beforeEach(function(done) {
        var promise,
          _this = this;
        promise = blog.create({
          title: expected,
          author: 'Mehfuz Hossain',
          body: 'Empty body'
        });
        return promise.then(function(result) {
          _id = result._id;
          return done();
        });
      });
      it('should return expected for permaLink', function(done) {
        var promise;
        promise = blog.findPost(helper.linkify('test post'));
        return promise.then(function(data) {
          data.post.title.should.equal(expected);
          console.log(data);
          return done();
        });
      });
      return afterEach(function(done) {
        return blog.deletePost(_id, function() {
          return done();
        });
      });
    });
  });

}).call(this);
