// Generated by CoffeeScript 1.3.3
(function() {
  var blog, mongoose;

  require("should");

  mongoose = require('mongoose');

  mongoose.connect('mongodb://localhost/lighter');

  blog = (require('../models/blog'))(mongoose);

  describe('create', function() {
    return describe('post', function() {
      before(function(done) {
        blog.create({
          title: "this is a test",
          author: "mehfuz",
          body: "some text"
        }, function(result) {
          console.log(result.id);
          return done();
        });
      });
      it('should assert find by title', function(done) {
        blog.findByTitle("test", function(data) {
          data.title.should.equal("this is a test");
          return done();
        });
      });
      return after(function(done) {
        console.log("remove all");
        blog.removeAll();
        done();
      });
    });
  });

}).call(this);
