// Generated by CoffeeScript 1.3.3
(function() {
  var blog, helper, mongoose;

  require('should');

  mongoose = require('mongoose');

  mongoose.connect('mongodb://localhost/lighter');

  blog = (require('../modules/blog'))(mongoose);

  helper = (require('../modules/helper'))();

  describe('blog', function() {
    return describe('create', function() {
      before(function(done) {
        blog.create({
          title: "this is a test",
          author: "mehfuz",
          body: "some text"
        }, function(result) {
          console.log(result.id);
          return done();
        });
      });
      it('should return the same for permalink', function(done) {
        blog.findByPermaLink(helper.linkify("this is a test"), function(data) {
          (data !== null).should.be["true"];
          return done();
        });
      });
      return after(function(done) {
        console.log("remove all");
        blog.removeAll();
        done();
      });
    });
  });

}).call(this);
