// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function() {
    var Helper, date, util;
    util = require('util');
    date = new Date();
    Helper = (function() {

      function Helper() {}

      Helper.prototype.linkify = function(source) {
        source = source.toLowerCase();
        source = source.replace(/^\s*|\s*$/g, '');
        source = source.replace(/:+/g, '');
        source = source.replace(/\s+/g, '-');
        source.replace(/[?#&]+/g, '');
        return util.format("%s/%s/%s", date.getFullYear(), date.getMonth() + 1, source);
      };

      return Helper;

    })();
    return new Helper();
  };

}).call(this);
