// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(settings) {
    var Request, user;
    user = require(__dirname + '/user')(settings);
    Request = (function() {

      function Request(settings) {
        this.settings = settings;
      }

      Request.prototype.validate = function(req, callback) {
        var authValue, buff, content, credentials;
        authValue = req.headers['authorization'];
        if (authValue.indexOf('Basic') >= 0) {
          buff = new Buffer(authValue.split(' ')[1], 'base64');
          content = buff.toString('utf8');
          if (content.indexOf(':') >= 0) {
            credentials = content.split(':');
            return user.find(credentials[0], credentials[1], function(data) {
              return callback(data);
            });
          }
        } else {
          return callback(null);
        }
      };

      return Request;

    })();
    return new Request(settings);
  };

}).call(this);
