// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(settings) {
    var Media;
    Media = (function() {

      function Media(settings) {
        this.media = settings.mongoose.model('media');
        this.helper = (require(__dirname + '/helper'))();
        this.settings = settings;
      }

      Media.prototype.create = function(res) {
        var link, promise,
          _this = this;
        promise = new this.settings.Promise;
        link = this.helper.linkify(res.slug);
        this.media.findOne(link, function(err, data) {
          var media;
          if (data === null) {
            media = new _this.media({
              id: res.id,
              url: link,
              type: res.type
            });
            return media.save(function(err, data) {
              return promise.resolve(data);
            });
          } else {
            return promise.resolve(data);
          }
        });
        return promise;
      };

      Media.prototype.get = function(url) {
        var promise,
          _this = this;
        promise = new this.settings.Promise;
        this.media.findOne({
          url: url
        }, function(err, data) {
          if (data !== null) {
            return promise.resolve(data);
          } else {
            return promise.resolve(null);
          }
        });
        return promise;
      };

      return Media;

    })();
    return new Media(settings);
  };

}).call(this);
