// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(settings) {
    var User;
    User = (function() {

      function User(settings) {
        this.settings = settings;
        this.user = settings.mongoose.model('user');
      }

      User.prototype.init = function(callback) {
        var _this = this;
        return this.user.findOne({
          username: settings.username
        }, function(err, data) {
          var user;
          if (data === null) {
            user = new _this.user({
              username: settings.username,
              password: settings.password,
              active: true,
              created: new Date()
            });
            return user.save(function(err, data) {
              if (err !== null) {
                throw err;
              }
              return callback(data);
            });
          } else {
            return callback(data);
          }
        });
      };

      User.prototype.find = function(username, password, callback) {
        return this.user.findOne({
          username: username,
          password: password
        }, function(err, data) {
          return callback(data);
        });
      };

      User.prototype["delete"] = function() {
        return this.user.remove(function() {});
      };

      return User;

    })();
    return new User(settings);
  };

}).call(this);
