// Generated by CoffeeScript 1.3.3
(function() {
  module.exports = function() {
    var Helper;
    Helper = (function() {

      function Helper() {}

      Helper.prototype.linkIt = function(source) {
        source = source.toLowerCase();
        source = source.replace(/\s+/g, '-');
        return source.replace(/[?#&]+/g, '');
      };

      return Helper;

    })();
    return new Helper();
  };

}).call(this);
