// Generated by CoffeeScript 1.4.0
(function() {
  var config, express;

  express = require('express');

  config = function(app) {
    app.configure(function() {
      app.set('port', process.env.PORT || 3000);
      app.set('views', __dirname + '/views');
      app.set('view engine', 'jade');
      app.use(express.favicon());
      app.use(express.logger('dev'));
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(app.router);
      app.use(require('less-middleware')({
        src: __dirname + '/public'
      }));
      app.use(express["static"](__dirname + '/public'));
      return app.locals.pretty = true;
    });
    return app.configure('production', function() {
      return app.use(express.errorHandler());
    });
  };

  module.exports = config;

}).call(this);
