// Generated by CoffeeScript 1.3.3
(function() {
  var routes,
    _this = this;

  routes = function(app, settings) {
    var blog;
    blog = (require(__dirname + '/modules/blog'))(settings.mongoose);
    app.get('/', function(req, res) {
      return blog.findAll(function(posts) {
        console.log(posts[0].title);
        return res.render('index', {
          title: 'Blog',
          posts: posts
        });
      });
    });
    return app.get('/post', function(req, res) {
      return res.render('post', {
        title: 'Blog',
        postedOn: new Date().toDateString()
      });
    });
  };

  module.exports = routes;

}).call(this);
