// Generated by CoffeeScript 1.3.3
(function() {
  var helper;

  helper = require('./helper');

  module.exports = function(mongoose) {
    var Blog;
    Blog = (function() {

      function Blog(mongoose) {
        var CategoriesSchema, CommentsSchema, ObjectId, PostSchema, Schema;
        Schema = mongoose.Schema;
        ObjectId = Schema.ObjectId;
        CategoriesSchema = new Schema({
          title: String
        });
        CommentsSchema = new Schema({
          title: String,
          text: String,
          date: Date
        });
        PostSchema = new Schema({
          author: String,
          title: String,
          body: String,
          date: Date,
          categories: [CategoriesSchema],
          comments: [CommentsSchema],
          publish: Boolean
        });
        this.Post = mongoose.model('post', PostSchema);
      }

      Blog.prototype.create = function(obj, callback) {
        var _this = this;
        return this.findByTitle(obj.title, function(data) {
          var post, title;
          if (data === null) {
            title = helper.linkify(title);
            post = new _this.Post({
              title: title,
              author: obj.author,
              body: obj.body,
              publish: 1,
              date: new Date()
            });
            return post.save(function(err, data) {
              if (err !== null) {
                throw err.message;
              }
              callback(data);
            });
          } else {
            throw 'duplicate post';
          }
        });
      };

      Blog.prototype.findByTitle = function(title, callback) {
        title = helper.linkify(title);
        return this.Post.findOne({
          title: title
        }, function(err, data) {
          if (err !== null) {
            throw err.message;
          }
          callback(data);
        });
      };

      Blog.prototype.removeAll = function() {
        return this.Post.remove({}, function() {
          return console.log("completed");
        });
      };

      return Blog;

    })();
    return new Blog(mongoose);
  };

}).call(this);
