// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(mongoose) {
    var Blog;
    Blog = (function() {

      function Blog(mongoose) {
        var CommentsSchema, ObjectId, PostSchema, Schema;
        Schema = mongoose.Schema;
        ObjectId = Schema.ObjectId;
        CommentsSchema = new Schema({
          title: String,
          text: String,
          date: Date
        });
        PostSchema = new Schema({
          author: {
            type: String,
            index: true
          },
          title: String,
          body: String,
          date: Date,
          comments: [CommentsSchema]
        });
        this.Post = mongoose.model('post', PostSchema);
      }

      Blog.prototype.createPost = function(obj, callback) {
        var post;
        post = new this.Post({
          title: obj.title,
          author: obj.author,
          body: obj.body,
          date: new Date()
        });
        return post.save(function(err, data) {
          callback(data);
        });
      };

      Blog.prototype.findByTitle = function(title, callback) {
        return this.Post.findOne({
          title: title
        }, function(err, data) {
          callback(data);
        });
      };

      Blog.prototype.removeAll = function() {
        return this.Post.remove({}, function() {
          return console.log("completed");
        });
      };

      return Blog;

    })();
    return new Blog(mongoose);
  };

}).call(this);
